### ISSUE TITLE
Update deprecated API removed at the end of 2019 in Gradle

### ISSUE THREAD

**Issue by vincentbrison** [sjcqs/gradle-config#7]
Thank you for your lib 🙃 

Using `com.android.tools.build:gradle:3.5.3` with `gradle-5.4.1`

A gradle sync will issue the following warning:
```
WARNING: API 'variant.getGenerateBuildConfig()' is obsolete and has been replaced with 'variant.getGenerateBuildConfigProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
```

To have more info about it we can run
`./gradlew sync -Pandroid.debug.obsoleteApi=true`

The result:
```
...
org.gradle.api.internal.tasks.DefaultTaskContainer.doCreate(DefaultTaskContainer.java:142)
org.gradle.api.internal.tasks.DefaultTaskContainer.create(DefaultTaskContainer.java:281)
org.gradle.api.tasks.TaskContainer$create.call(null:-1)
org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135)
com.sjcqs.android.config.ConfigPlugin.createCodeGenerationTask(ConfigPlugin.groovy:67)
```

I guess the API to update resides within `createCodeGenerationTask` task, but it just a guess.

Additionally maybe we can implement a test which run `./gradlew sync -Pandroid.debug.obsoleteApi=true` to ensure to deprecated API is used?

**Comment by sjcqs** [comment]
> I guess the API to update resides within createCodeGenerationTask task, but it just a guess.

I'll take a look ;) 

> Additionally maybe we can implement a test which run ./gradlew sync -Pandroid.debug.obsoleteApi=true to ensure to deprecated API is used?

Great idea, I'll take a look
